FROM node:21-slim
# 22 會出現 bug

RUN apt-get update && \
    apt-get install -y python3 python3-pip git wget curl jq && \
    rm -rf /var/lib/apt/lists/*

# 安裝 git 與其他基本工具
RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq &&\
chmod +x /usr/local/bin/yq

RUN wget https://github.com/jqlang/jq/releases/download/jq-1.8.0/jq-linux-amd64 -O  /usr/local/bin/jq &&\
chmod +x /usr/local/bin/jq

WORKDIR /app

# # 安裝 semantic-release 及其 plugin
# RUN npm install -g \
#     semantic-release \
#     @semantic-release/git \
#     @semantic-release/changelog \
#     @semantic-release/gitlab \
#     @semantic-release/commit-analyzer \
#     @semantic-release/release-notes-generator

# # 預設命令（可在 CI 中被 override）
# CMD ["semantic-release", "--version"]

# 安裝指定版本的 semantic-release 與對應 plugin
# RUN npm install -g \
#     semantic-release@24 \
#     @semantic-release/git@10 \
#     @semantic-release/changelog@6 \
#     @semantic-release/gitlab@6 \
#     @semantic-release/commit-analyzer@9 \
#     @semantic-release/release-notes-generator@11

RUN npm install -g \
    semantic-release@24 \
    @semantic-release/git \
    @semantic-release/changelog \
    @semantic-release/gitlab@10 \
    @semantic-release/commit-analyzer \
    @semantic-release/release-notes-generator \
    @semantic-release/exec \
    conventional-changelog-conventionalcommits

RUN python3 -m pip install --break-system-packages ansible

# 預設執行 npx semantic-release（可在 CI 中被覆蓋）
CMD ["npx", "semantic-release"]
