services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
      PGPASS_FILE: "/pgadmin4/.pgpass"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/.pgpass:/pgadmin4/.pgpass

  # web:
  #   build: .
  #   command: uvicorn virtflow.asgi:application --host 0.0.0.0 --port 8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_NAME=${POSTGRES_DB}
  #     - DATABASE_USER=${POSTGRES_USER}
  #     - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
  #     - DATABASE_HOST=postgres
  