services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PIP_INDEX_URL: ""
        PIP_TRUSTED_HOST: ""
        OVERWRITE_APT_SOURCE: "false"
        APT_SOURCE_CONTEXT: |
          deb [trusted=yes] http://
    volumes:
      - ./:/workspaces/inventory-api:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      # - ~/.vscode-server:/home/vscode/.vscode-server
      # - ~/.gitconfig:/home/vscode/.gitconfig:ro
    command: sleep infinity
    # environment:
    #   - PYTHONPATH=/workspace
    #   - DJANGO_SETTINGS_MODULE=virtflow.settings
