services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PIP_INDEX_URL: ""
        PIP_TRUSTED_HOST: ""
        OVERWRITE_APT_SOURCE: "false"
        APT_SOURCE_CONTENT: |
          deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          deb [trusted=yes] http://ppa.launchpad.net/apt-fast/stable/ubuntu focal main
          deb [trusted=yes] https://packages.microsoft.com/repos/vscode stable main
          deb [trusted=yes] https://baltocdn.com/helm/stable/debian/ all main

    volumes:
      - ~/.ssh:/home/vscode/.ssh:ro
      # - ~/.vscode-server:/home/vscode/.vscode-server
      # - ./:/workspaces/${PROJECT_BASE_DIR}:cached
      # - ~/.gitconfig:/home/vscode/.gitconfig:ro
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
