{{- if .Values.vaultSecret.create }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "inventory-api.secretName" . }}
  namespace: {{ .Values.configMap.namespace | default .Release.Namespace }}
  labels:
    {{- include "inventory-api.labels" . | nindent 4 }}
spec:
  path: {{ required "vaultSecret.spec.path is required" .Values.vaultSecret.spec.path }}
  type: {{ default "Opaque" .Values.vaultSecret.spec.type }}
  {{- with .Values.vaultSecret.spec.keys }}
  keys:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.vaultSecret.spec.isBinary }}
  isBinary: {{ . }}
  {{- end }}
  {{- with .Values.vaultSecret.spec.reconcileStrategy }}
  reconcileStrategy: {{ . }}
  {{- end }}
  {{- with .Values.vaultSecret.spec.templates }}
  templates:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
