{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.secretName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "api-service.postgresPassword" . }}
  DJANGO_SUPERUSER_PASSWORD: {{ include "api-service.djangoSuperuserPassword" . }}
  DJANGO_SECRET_KEY: {{ include "api-service.djangoSecretKey" . }}
  DJANGO_BACKDOOR_API_TOKEN: {{ include "api-service.djangoBackdoorApiToken" . }}
  PGADMIN_DEFAULT_PASSWORD: {{ include "api-service.pgadminPassword" . }}
{{- range $key, $value := .Values.secrets.data }}
{{- if and (ne $key "POSTGRES_PASSWORD") (ne $key "DJANGO_SUPERUSER_PASSWORD") (ne $key "DJANGO_SECRET_KEY") (ne $key "DJANGO_BACKDOOR_API_TOKEN") (ne $key "PGADMIN_DEFAULT_PASSWORD") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }} 
{{- end }}
