{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-api.secretName" . }}
  labels:
    {{- include "inventory-api.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "inventory-api.postgresPassword" . }}
  DJANGO_SUPERUSER_PASSWORD: {{ include "inventory-api.djangoSuperuserPassword" . }}
  DJANGO_SECRET_KEY: {{ include "inventory-api.djangoSecretKey" . }}
  DJANGO_BACKDOOR_API_TOKEN: {{ include "inventory-api.djangoBackdoorApiToken" . }}
  PGADMIN_DEFAULT_PASSWORD: {{ include "inventory-api.pgadminPassword" . }}
{{- range $key, $value := .Values.secrets.data }}
{{- if and (ne $key "POSTGRES_PASSWORD") (ne $key "DJANGO_SUPERUSER_PASSWORD") (ne $key "DJANGO_SECRET_KEY") (ne $key "DJANGO_BACKDOOR_API_TOKEN") (ne $key "PGADMIN_DEFAULT_PASSWORD") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }} 
{{- end }}
