{{- if .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name | default (printf "%s-vs" (include "inventory-api.fullname" .)) }}
  namespace: {{ .Values.istio.virtualService.namespace | default .Release.Namespace }}
  labels:
    {{- include "inventory-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: virtualservice
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  {{- range .Values.istio.virtualService.http }}
  - match:
    {{- range .match }}
    - uri:
        {{- if .uri.prefix }}
        prefix: {{ .uri.prefix | quote }}
        {{- else if .uri.exact }}
        exact: {{ .uri.exact | quote }}
        {{- else if .uri.regex }}
        regex: {{ .uri.regex | quote }}
        {{- end }}
      {{- if .headers }}
      headers:
        {{- toYaml .headers | nindent 8 }}
      {{- end }}
      {{- if .queryParams }}
      queryParams:
        {{- toYaml .queryParams | nindent 8 }}
      {{- end }}
    {{- end }}
    route:
    {{- range .route }}
    - destination:
        host: {{ .destination.host | default (include "inventory-api.fullname" $) | quote }}
        {{- if .destination.port }}
        port:
          number: {{ .destination.port.number }}
        {{- end }}
        {{- if .destination.subset }}
        subset: {{ .destination.subset | quote }}
        {{- end }}
      {{- if .weight }}
      weight: {{ .weight }}
      {{- end }}
    {{- end }}
    {{- if .timeout }}
    timeout: {{ .timeout }}
    {{- end }}
    {{- if .retries }}
    retries:
      {{- if .retries.attempts }}
      attempts: {{ .retries.attempts }}
      {{- end }}
      {{- if .retries.perTryTimeout }}
      perTryTimeout: {{ .retries.perTryTimeout }}
      {{- end }}
      {{- if .retries.retryOn }}
      retryOn: {{ .retries.retryOn | quote }}
      {{- end }}
    {{- end }}
    {{- if .fault }}
    fault:
      {{- toYaml .fault | nindent 6 }}
    {{- end }}
    {{- if .mirror }}
    mirror:
      {{- toYaml .mirror | nindent 6 }}
    {{- end }}
    {{- if .corsPolicy }}
    corsPolicy:
      {{- toYaml .corsPolicy | nindent 6 }}
    {{- end }}
    {{- if .headers }}
    headers:
      {{- if .headers.request }}
      request:
        {{- toYaml .headers.request | nindent 8 }}
      {{- end }}
      {{- if .headers.response }}
      response:
        {{- toYaml .headers.response | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
